services:
  nginx:
    image: nginx:latest
    container_name: mrd
    expose:
      - "80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-node
      - backend-python
    networks:
      - my-research-digest-network
      - main-network
    restart: unless-stopped

  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: my-research-digest-backend-node
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - my-research-digest-network
    restart: unless-stopped

  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: my-research-digest-backend-python
    env_file:
      - .env
    depends_on:
      - backend-node # backend-python needs node API backend for API calls
    networks:
      - my-research-digest-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_AUTH0_REDIRECT_URI=${VITE_AUTH0_REDIRECT_URI}
        - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
        - VITE_MONGO_API_URL=${VITE_MONGO_API_URL}
        - VITE_ADMIN_EMAILS=${VITE_ADMIN_EMAILS}
    container_name: my-research-digest-frontend
    depends_on:
      - backend-node # Frontend needs backend for API calls
    networks:
      - my-research-digest-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: my-research-digest-mongodb
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - my-research-digest-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  my-research-digest-network:
    driver: bridge

  main-network:
    name: main-network
    external: true
