services:
  nginx:
    image: nginx:latest
    container_name: my-research-digest-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-node
      - backend-python
    networks:
      - my-research-digest-network

  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: my-research-digest-backend-node
    env_file:
      - .development.env
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - my-research-digest-network

  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: my-research-digest-backend-python
    env_file:
      - .development.env
    networks:
      - my-research-digest-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_AUTH0_REDIRECT_URI=${VITE_AUTH0_REDIRECT_URI}
        - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
        - VITE_MONGO_API_URL=${VITE_MONGO_API_URL}
        - VITE_ADMIN_EMAILS=${VITE_ADMIN_EMAILS}
    container_name: my-research-digest-frontend
    depends_on:
      - backend-node # Frontend needs backend for API calls
    networks:
      - my-research-digest-network

  mongodb:
    image: mongo:latest
    container_name: my-research-digest-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - my-research-digest-network

volumes:
  mongodb_data:

networks:
  my-research-digest-network:
    driver: bridge
